services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        ports:
            - "5432:5432"

    frontend:
        build: .
        restart: always
        ports: 
            - "3000:3000"

    backend:
        build: backend
        depends_on:
            - postgres
        restart: always
        ports:
            - "8000:8080"