# fly.toml app configuration file generated for ch-backend on 2023-05-29T06:25:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ch-backend"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
